/*
 * @(#)src/demo/jni/FileStat.h, dadev, dxdev, 20050630 1.5
 * ===========================================================================
 * Licensed Materials - Property of IBM
 * "Restricted Materials of IBM"
 *
 * IBM SDK, Java(tm) 2 Technology Edition, v5.0
 * (C) Copyright IBM Corp. 1998, 2005. All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 * ===========================================================================
 */

/*
 * ===========================================================================
 (C) Copyright Sun Microsystems Inc, 1992, 2004. All rights reserved.
 * ===========================================================================
 */




/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileStat */

#ifndef _Included_FileStat
#define _Included_FileStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileStat
 * Method:    nativeFileStat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FileStat_nativeFileStat
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
